"""Add nullable to author

Revision ID: 441254afdcfa
Revises: 0347528e1013
Create Date: 2022-07-12 12:00:47.825680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441254afdcfa'
down_revision = '0347528e1013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
